# Generated by Django 4.0.2 on 2022-04-15 23:11

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('embedcode', models.TextField(validators=[videos.models.validate_embedcode])),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
