# Generated by Django 4.0.2 on 2022-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
