# Generated by Django 4.0.2 on 2022-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_alter_rezept_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='thumbnail',
            field=models.ImageField(upload_to='rezepte/static/'),
        ),
    ]
