# Generated by Django 4.0.2 on 2022-02-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0003_alter_rezept_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='rezept',
            options={'verbose_name_plural': 'Rezepte'},
        ),
        migrations.RemoveField(
            model_name='kategorie',
            name='rezepte',
        ),
        migrations.AddField(
            model_name='rezept',
            name='kategorien',
            field=models.ManyToManyField(blank=True, to='rezepte.Kategorie'),
        ),
        migrations.AlterField(
            model_name='rezept',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='rezepte/static/'),
        ),
    ]
