# Generated by Django 4.0.2 on 2022-02-20 17:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0004_alter_kategorie_options_alter_rezept_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='content',
            field=tinymce.models.HTMLField(default='placeholder'),
            preserve_default=False,
        ),
    ]
