# Generated by Django 4.0.2 on 2022-03-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0006_remove_rezept_text_alter_rezept_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='beschreibung',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
