# Generated by Django 4.0.2 on 2022-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0009_favorite_delete_rezeptprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'favorites'), name='unique_favorite'),
        ),
    ]
