# Generated by Django 4.0.2 on 2022-03-16 22:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rezepte', '0011_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezept',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
