# Generated by Django 4.0.2 on 2022-04-04 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0013_favorite_favorite_unique_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezept',
            options={},
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
