# Generated by Django 4.0.2 on 2022-04-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0015_remove_rezept_favorited_by_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_favorite',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='favorites',
            new_name='rezept',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'rezept'), name='unique_favorite'),
        ),
    ]
