# Generated by Django 4.0.2 on 2022-04-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0016_remove_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rezept',
            options={'verbose_name_plural': 'Rezepte'},
        ),
    ]
